spring.application.name=parasempredois

# Default profile for local development
spring.profiles.active=local

# Defaults can be overridden by environment variables in PRD
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/parasempredois}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
